### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Demian101** [Aztec-alpha/pre-requisites#4]
Roadmap：
1. reproduce zkmessage.xyz
2. check membership using Merkle tree
3. update mimc to ECDSA signature verification
4. Proofs of Property of Identity via a onchain DAO contract deployed on Aztec

Ref: https://0xparc.org/blog/zk-group-sigs

**Comment by Demian101** [comment]
- [x] @dajuguan: zkp Circuit writing & review
- [x] @JustXxx  authentication part (ECDSA?)
- [x] @Demian101 : Interaction between front-end and Aztec
- [ ] pending: publish progress on discord once finished demo

**Comment by pochenai** [comment]
- Implement a noir contract to register group and get group members @JustXxx

**Comment by Demian101** [comment]
<img width="1111" alt="image" src="https://github.com/Aztec-alpha/pre-requisites/assets/33189338/2ef8770c-9144-4aba-83df-a4edd9a1d046">


zkmessage
	Group
		One Group
		#[public]
add_member() onlyOwner
		Group Member 
Verification
			#[private]
minters: Map<AztecAddress, PublicMutable<bool>>,
assert(storage.minters.at(context.msg_sender()).read(), "caller is not minter");
			Message is Public
				Frontend Read the Message (Noir.js)
		read_message.
		Work
			API interface Design @Demian
			Aztec-contract.js Research @Po
		Wednesday 3.6
